const STORAGE_KEY = "bori-v12-state";
const emptyState = { books: [], expenses: [], incomes: [], budgets: [], messages: [] };
const categoryMeta = {
  餐飲:{icon:"🍜",color:"#ef9b67"},交通:{icon:"🚗",color:"#67a4ab"},娛樂:{icon:"🎬",color:"#a288c3"},購物:{icon:"🛍️",color:"#dfb451"},生活:{icon:"🏠",color:"#7d9d68"},旅行:{icon:"✈️",color:"#6d91c6"},其他:{icon:"✨",color:"#aaa096"}
};
const stickers = [
  {emoji:"🐻👌",text:"OK！"},{emoji:"🐻💛",text:"謝謝～"},{emoji:"🐻🙌",text:"收到～"},{emoji:"🐻💸",text:"已付款"},
  {emoji:"🐻🍚",text:"今天我請客！"},{emoji:"🐻😂",text:"哈哈哈哈"},{emoji:"🐻❤️",text:"愛你"},{emoji:"🐻📒",text:"記得記帳喔"}
];
let state = loadState();
let activeBookId = state.books[0]?.id || null;
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const money = n => `$${Math.round(Number(n)||0).toLocaleString("zh-TW")}`;
const uuid = () => crypto.randomUUID?.() || `id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const bookById = id => state.books.find(b => b.id === id);
const monthKey = d => new Date(d).toISOString().slice(0,7);
const currentMonth = () => new Date().toISOString().slice(0,7);
const escapeHTML = v => String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

function loadState(){ try{ const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)); if(saved) return {...structuredClone(emptyState),...saved}; }catch(e){console.warn(e)} return structuredClone(emptyState); }
function saveState(){ localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); }
function showToast(msg){ const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove("show"),1800); }
function openDialog(id){ const d=document.getElementById(id); if(!state.books.length && id!=="bookDialog") return openDialog("bookDialog"); fillBookSelects(); d?.showModal(); }
function closeDialog(id){ document.getElementById(id)?.close(); }
function goTo(id){ $$(".page").forEach(p=>p.classList.toggle("active",p.id===id)); $$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.page===id)); renderAll(); scrollTo({top:0,behavior:"smooth"}); }
function recordsForBook(bookId){ return { expenses:state.expenses.filter(x=>x.bookId===bookId), incomes:state.incomes.filter(x=>x.bookId===bookId), budgets:state.budgets.filter(x=>x.bookId===bookId), messages:state.messages.filter(x=>x.bookId===bookId) }; }
function activeBook(){ if(!activeBookId||!bookById(activeBookId)) activeBookId=state.books[0]?.id||null; return bookById(activeBookId); }
function fillBookSelects(){ const options=state.books.map(b=>`<option value="${b.id}">${b.icon} ${escapeHTML(b.name)}</option>`).join(""); ["bookInput","incomeBookInput","budgetBookInput","chatBookSelect"].forEach(id=>{const el=document.getElementById(id);if(el){el.innerHTML=options;if(activeBookId)el.value=activeBookId;}}); if(activeBookId) updateMembers(activeBookId); }
function updateMembers(bookId){ const b=bookById(bookId); const members=b?.members?.length?b.members:["我"]; $("#payerInput").innerHTML=members.map(n=>`<option>${escapeHTML(n)}</option>`).join(""); $("#participantChecks").innerHTML=members.map(n=>`<label><input type="checkbox" value="${escapeHTML(n)}" checked><span>${escapeHTML(n)}</span></label>`).join(""); }

function renderAll(){ renderHome();renderAdd();renderChat();renderAnalysis();fillBookSelects(); }
function renderHome(){ const has=state.books.length>0; $("#homeEmpty").classList.toggle("hidden",has);$("#homeDashboard").classList.toggle("hidden",!has);if(!has)return; const b=activeBook();const r=recordsForBook(b.id);const m=currentMonth();const expenses=r.expenses.filter(x=>monthKey(x.date)===m);const incomes=r.incomes.filter(x=>monthKey(x.date)===m);const exp=expenses.reduce((s,x)=>s+x.amount,0);const inc=incomes.reduce((s,x)=>s+x.amount,0);const bud=r.budgets.reduce((s,x)=>s+x.amount,0);$("#homeBookName").textContent=`${b.icon} ${b.name}`;$("#incomeTotal").textContent=money(inc);$("#expenseTotal").textContent=money(exp);$("#budgetTotal").textContent=money(bud);$("#availableAmount").textContent=money(bud?Math.max(bud-exp,0):inc-exp);$("#budgetHint").textContent=bud?`預算已使用 ${Math.min(100,Math.round(exp/bud*100))}%`:`目前結餘 ${money(inc-exp)}`;const last=r.messages.at(-1);$("#chatSummary").textContent=last?last.type==="sticker"?last.text:last.content:"還沒有聊天訊息";renderBudgets(b.id);const records=[...r.expenses.map(x=>({...x,kind:"expense"})),...r.incomes.map(x=>({...x,kind:"income"}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,5);$("#recentList").innerHTML=records.length?records.map(recordHTML).join(""):`<div class="empty-state compact"><p>還沒有收入或支出紀錄。</p></div>`; }
function renderBudgets(bookId){ const r=recordsForBook(bookId);const m=currentMonth();const expenses=r.expenses.filter(x=>monthKey(x.date)===m);const el=$("#budgetPreview");if(!r.budgets.length){el.innerHTML=`<div class="empty-state compact"><p>尚未設定預算，先為常用分類設定上限吧。</p></div>`;return;}el.innerHTML=r.budgets.map(b=>{const used=expenses.filter(x=>x.category===b.category).reduce((s,x)=>s+x.amount,0);const pct=b.amount?Math.min(120,used/b.amount*100):0;const meta=categoryMeta[b.category]||categoryMeta.其他;return `<article class="budget-card"><div class="budget-head"><span>${meta.icon} ${b.category}</span><strong>${money(used)} / ${money(b.amount)}</strong></div><div class="progress"><i class="${pct>=100?'over':''}" style="width:${Math.min(100,pct)}%"></i></div><small>${pct>=100?'已超出預算':`還可以使用 ${money(Math.max(b.amount-used,0))}`}</small></article>`}).join(""); }
function recordHTML(x){ const income=x.kind==="income";const meta=income?{icon:"💰",color:"#7fa56a"}:(categoryMeta[x.category]||categoryMeta.其他);return `<article class="record"><div class="record-icon" style="background:${meta.color}20">${meta.icon}</div><div><strong>${escapeHTML(x.title)}</strong><small>${escapeHTML(x.category)} · ${new Date(x.date).toLocaleDateString("zh-TW")}</small></div><b class="${income?'income-text':''}">${income?'+':'-'}${money(x.amount)}</b></article>`; }
function renderAdd(){ const has=state.books.length>0;$("#addEmpty").classList.toggle("hidden",has);$("#addContent").classList.toggle("hidden",!has);if(has){activeBook();fillBookSelects();updateMembers(activeBookId);} }
function renderChat(){ const has=state.books.length>0;$("#chatEmpty").classList.toggle("hidden",has);$("#chatContent").classList.toggle("hidden",!has);if(!has)return;const b=activeBook();$("#chatBookTitle").textContent=`${b.icon} ${b.name}`;const msgs=recordsForBook(b.id).messages;$("#messageList").innerHTML=msgs.length?msgs.map(m=>m.type==="sticker"?`<div class="message mine sticker-message"><span>${m.emoji}</span><strong>${escapeHTML(m.text)}</strong><small>${new Date(m.date).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})}</small></div>`:`<div class="message mine"><p>${escapeHTML(m.content)}</p><small>${new Date(m.date).toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})}</small></div>`).join(""):`<div class="chat-welcome"><span>🐻</span><p>這裡是你們的共同聊天室。<br>可以聊天，也可以傳送 BORI 貼圖。</p></div>`;$("#stickerTray").innerHTML=stickers.map((s,i)=>`<button type="button" data-sticker="${i}"><span>${s.emoji}</span><small>${s.text}</small></button>`).join("");setTimeout(()=>{$("#messageList").scrollTop=$("#messageList").scrollHeight},0); }
function renderAnalysis(){ const has=state.expenses.length||state.incomes.length||state.budgets.length;$("#analysisEmpty").classList.toggle("hidden",!!has);$("#analysisContent").classList.toggle("hidden",!has);if(!has)return;const b=activeBook()||state.books[0];const r=b?recordsForBook(b.id):{expenses:state.expenses,incomes:state.incomes};const m=currentMonth();const expenses=r.expenses.filter(x=>monthKey(x.date)===m);const incomes=r.incomes.filter(x=>monthKey(x.date)===m);const exp=expenses.reduce((s,x)=>s+x.amount,0);const inc=incomes.reduce((s,x)=>s+x.amount,0);$("#analysisIncome").textContent=money(inc);$("#analysisExpense").textContent=money(exp);$("#analysisNet").textContent=money(inc-exp);$("#donutTotal").textContent=money(exp);const grouped={};expenses.forEach(x=>grouped[x.category]=(grouped[x.category]||0)+x.amount);const entries=Object.entries(grouped).sort((a,b)=>b[1]-a[1]);let cursor=0;const segments=entries.map(([c,v])=>{const s=cursor;cursor+=exp?v/exp*360:0;return `${(categoryMeta[c]||categoryMeta.其他).color} ${s}deg ${cursor}deg`});$("#donutChart").style.background=segments.length?`conic-gradient(${segments.join(",")})`:"#eee7dc";$("#categoryLegend").innerHTML=entries.length?entries.map(([c,v])=>`<div class="legend-row"><i style="background:${(categoryMeta[c]||categoryMeta.其他).color}"></i><span>${c}</span><strong>${Math.round(v/exp*100)}%</strong></div>`).join(""):`<p class="muted">尚無支出分類</p>`;$("#incomeList").innerHTML=incomes.length?incomes.sort((a,b)=>new Date(b.date)-new Date(a.date)).map(x=>recordHTML({...x,kind:"income"})).join(""):`<div class="empty-state compact"><p>本月尚無收入。</p></div>`; }

$$('[data-page]').forEach(b=>b.addEventListener('click',()=>goTo(b.dataset.page)));
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openDialog(b.dataset.open)));
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.dataset.close)));
$("#bookInput").addEventListener("change",e=>{activeBookId=e.target.value;updateMembers(activeBookId)});
$("#chatBookSelect").addEventListener("change",e=>{activeBookId=e.target.value;renderAll()});

$("#bookForm").addEventListener("submit",e=>{e.preventDefault();const name=$("#newBookName").value.trim();if(!name)return;const icon=document.querySelector('[name="bookType"]:checked').value;let members=$("#newBookMembers").value.split(/[，,]/).map(x=>x.trim()).filter(Boolean);if(!members.includes("我"))members.unshift("我");const book={id:uuid(),name,icon,members:[...new Set(members)],createdAt:new Date().toISOString()};state.books.push(book);activeBookId=book.id;saveState();e.target.reset();$("#newBookMembers").value="我";closeDialog("bookDialog");renderAll();showToast("共同帳本建立完成 🌾")});
$("#expenseForm").addEventListener("submit",e=>{e.preventDefault();const participants=$$("#participantChecks input:checked").map(x=>x.value);if(!participants.length)return showToast("請選擇參與者");state.expenses.push({id:uuid(),bookId:$("#bookInput").value,title:$("#titleInput").value.trim(),amount:Number($("#amountInput").value),category:$("#categoryInput").value,payer:$("#payerInput").value,participants,note:$("#noteInput").value.trim(),date:new Date().toISOString()});activeBookId=$("#bookInput").value;saveState();e.target.reset();renderAll();goTo("homePage");showToast("支出已儲存")});
$("#incomeForm").addEventListener("submit",e=>{e.preventDefault();state.incomes.push({id:uuid(),bookId:$("#incomeBookInput").value,title:$("#incomeTitle").value.trim(),amount:Number($("#incomeAmount").value),category:$("#incomeCategory").value,date:new Date().toISOString()});activeBookId=$("#incomeBookInput").value;saveState();e.target.reset();closeDialog("incomeDialog");renderAll();showToast("收入已儲存 💰")});
$("#budgetForm").addEventListener("submit",e=>{e.preventDefault();const bookId=$("#budgetBookInput").value;const category=$("#budgetCategory").value;const existing=state.budgets.find(x=>x.bookId===bookId&&x.category===category);if(existing)existing.amount=Number($("#budgetAmount").value);else state.budgets.push({id:uuid(),bookId,category,amount:Number($("#budgetAmount").value)});activeBookId=bookId;saveState();e.target.reset();closeDialog("budgetDialog");renderAll();showToast("預算已更新 🎯")});
$("#chatForm").addEventListener("submit",e=>{e.preventDefault();const content=$("#messageInput").value.trim();if(!content)return;state.messages.push({id:uuid(),bookId:activeBookId,type:"text",content,date:new Date().toISOString()});$("#messageInput").value="";saveState();renderAll()});
$("#stickerBtn").addEventListener("click",()=>$("#stickerTray").classList.toggle("hidden"));
$("#stickerTray").addEventListener("click",e=>{const btn=e.target.closest("[data-sticker]");if(!btn)return;const s=stickers[Number(btn.dataset.sticker)];state.messages.push({id:uuid(),bookId:activeBookId,type:"sticker",emoji:s.emoji,text:s.text,date:new Date().toISOString()});saveState();$("#stickerTray").classList.add("hidden");renderAll()});
$("#resetBtn").addEventListener("click",()=>{if(!confirm("確定清除所有 BORI 資料嗎？"))return;state=structuredClone(emptyState);activeBookId=null;saveState();renderAll();goTo("homePage");showToast("資料已清除")});

renderAll();
function finishSplash(){const s=$("#splashScreen");if(!s)return;s.classList.add("hide");document.body.classList.remove("splash-lock");setTimeout(()=>s.remove(),650)}
document.body.classList.add("splash-lock");addEventListener("load",()=>setTimeout(finishSplash,1900));setTimeout(finishSplash,3500);
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));
